In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7059, 8728, 9514, 1195],
 [7059, 8728, 9514, 6222],
 [7059, 3184, 9514, 9453],
 [3331, 5490, 3654, 8117, 5001],
 [3331, 5490, 3654, 8117, 5485],
 [5915, 7059, 1522, 9514, 7726],
 [7502, 2217, 4444, 8117]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7059 8728 9514 1195]
 [   0    0    0    0 7059 8728 9514 6222]
 [   0    0    0    0 7059 3184 9514 9453]
 [   0    0    0 3331 5490 3654 8117 5001]
 [   0    0    0 3331 5490 3654 8117 5485]
 [   0    0    0 5915 7059 1522 9514 7726]
 [   0    0    0    0 7502 2217 4444 8117]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 318ms/step


array([[[-4.90263849e-03, -1.01376548e-02,  3.48993652e-02,
         -4.48388569e-02, -2.95124054e-02,  1.71509869e-02,
          2.25107186e-02,  2.67910101e-02,  1.36280917e-02,
         -2.84590963e-02],
        [-4.90263849e-03, -1.01376548e-02,  3.48993652e-02,
         -4.48388569e-02, -2.95124054e-02,  1.71509869e-02,
          2.25107186e-02,  2.67910101e-02,  1.36280917e-02,
         -2.84590963e-02],
        [-4.90263849e-03, -1.01376548e-02,  3.48993652e-02,
         -4.48388569e-02, -2.95124054e-02,  1.71509869e-02,
          2.25107186e-02,  2.67910101e-02,  1.36280917e-02,
         -2.84590963e-02],
        [-4.90263849e-03, -1.01376548e-02,  3.48993652e-02,
         -4.48388569e-02, -2.95124054e-02,  1.71509869e-02,
          2.25107186e-02,  2.67910101e-02,  1.36280917e-02,
         -2.84590963e-02],
        [ 4.93058302e-02,  1.69958808e-02, -1.68357715e-02,
          1.03602558e-03, -1.94978602e-02,  1.42518617e-02,
         -9.30777937e-03, -3.12557369e-02,  2.153226

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7059, 8728, 9514, 1195])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 100ms/step


array([[-0.00490264, -0.01013765,  0.03489937, -0.04483886, -0.02951241,
         0.01715099,  0.02251072,  0.02679101,  0.01362809, -0.0284591 ],
       [-0.00490264, -0.01013765,  0.03489937, -0.04483886, -0.02951241,
         0.01715099,  0.02251072,  0.02679101,  0.01362809, -0.0284591 ],
       [-0.00490264, -0.01013765,  0.03489937, -0.04483886, -0.02951241,
         0.01715099,  0.02251072,  0.02679101,  0.01362809, -0.0284591 ],
       [-0.00490264, -0.01013765,  0.03489937, -0.04483886, -0.02951241,
         0.01715099,  0.02251072,  0.02679101,  0.01362809, -0.0284591 ],
       [ 0.04930583,  0.01699588, -0.01683577,  0.00103603, -0.01949786,
         0.01425186, -0.00930778, -0.03125574,  0.02153226,  0.02118086],
       [-0.02329133, -0.00128443,  0.04477203,  0.02723287,  0.04014932,
        -0.02194684,  0.03559306,  0.00038618, -0.04744641,  0.00160283],
       [ 0.02663145,  0.00258652, -0.0101694 ,  0.02685964,  0.03107485,
         0.03758292, -0.01985178,  0.00181834